services:
  - type: web
    name: news-api
    env: docker
    rootDir: .
    dockerfilePath: src/Services/NewsService/News.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: users-api
    env: docker
    rootDir: .
    dockerfilePath: src/Services/UsersService/Users.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: notification-api
    env: docker
    rootDir: .
    dockerfilePath: src/Services/NotificationService/Notification.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
